{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e72d5ce0-59ab-45b3-9874-dd6da7048f5e",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "from datetime import datetime, timedelta\n",
    "\n",
    "def create_lag_features(df, target_cols, lags=[1, 7, 30]):\n",
    "    \"\"\"Create lag features for time series\"\"\"\n",
    "    df_copy = df.copy()\n",
    "    for col in target_cols:\n",
    "        for lag in lags:\n",
    "            df_copy[f'{col}_lag_{lag}'] = df_copy[col].shift(lag)\n",
    "    return df_copy\n",
    "\n",
    "def create_rolling_features(df, target_cols, windows=[7, 30]):\n",
    "    \"\"\"Create rolling statistics\"\"\"\n",
    "    df_copy = df.copy()\n",
    "    for col in target_cols:\n",
    "        for window in windows:\n",
    "            df_copy[f'{col}_rolling_mean_{window}'] = df_copy[col].rolling(window=window).mean()\n",
    "            df_copy[f'{col}_rolling_std_{window}'] = df_copy[col].rolling(window=window).std()\n",
    "    return df_copy\n",
    "\n",
    "def add_time_features(df, date_col='Date'):\n",
    "    \"\"\"Add time-based features\"\"\"\n",
    "    df_copy = df.copy()\n",
    "    df_copy['Year'] = df_copy[date_col].dt.year\n",
    "    df_copy['Month'] = df_copy[date_col].dt.month\n",
    "    df_copy['Day'] = df_copy[date_col].dt.day\n",
    "    df_copy['DayOfWeek'] = df_copy[date_col].dt.dayofweek\n",
    "    df_copy['Quarter'] = df_copy[date_col].dt.quarter\n",
    "    df_copy['WeekOfYear'] = df_copy[date_col].dt.isocalendar().week.astype(int)\n",
    "    \n",
    "    # Cyclical encoding\n",
    "    df_copy['Month_Sin'] = np.sin(2 * np.pi * df_copy['Month'] / 12)\n",
    "    df_copy['Month_Cos'] = np.cos(2 * np.pi * df_copy['Month'] / 12)\n",
    "    \n",
    "    return df_copy\n",
    "\n",
    "def add_holiday_indicators(df, date_col='Date'):\n",
    "    \"\"\"Add Sri Lankan holiday indicators\"\"\"\n",
    "    df_copy = df.copy()\n",
    "    \n",
    "    def is_sinhala_tamil_new_year(date):\n",
    "        return (date.month == 4) and (date.day in [13, 14])\n",
    "    \n",
    "    def is_vesak(date):\n",
    "        return (date.month == 5) and (15 <= date.day <= 25)\n",
    "    \n",
    "    def is_christmas(date):\n",
    "        return (date.month == 12) and (date.day == 25)\n",
    "    \n",
    "    def is_new_year(date):\n",
    "        return (date.month == 1) and (date.day == 1)\n",
    "    \n",
    "    df_copy['Is_Sinhala_Tamil_New_Year'] = df_copy[date_col].apply(is_sinhala_tamil_new_year).astype(int)\n",
    "    df_copy['Is_Vesak'] = df_copy[date_col].apply(is_vesak).astype(int)\n",
    "    df_copy['Is_Christmas'] = df_copy[date_col].apply(is_christmas).astype(int)\n",
    "    df_copy['Is_New_Year'] = df_copy[date_col].apply(is_new_year).astype(int)\n",
    "    df_copy['Is_Weekend'] = (df_copy[date_col].dt.dayofweek >= 5).astype(int)\n",
    "    \n",
    "    return df_copy\n",
    "\n",
    "def add_crisis_indicators(df, date_col='Date'):\n",
    "    \"\"\"Add crisis period indicators\"\"\"\n",
    "    df_copy = df.copy()\n",
    "    df_copy['Is_COVID_Period'] = ((df_copy[date_col] >= '2020-03-01') & \n",
    "                                   (df_copy[date_col] <= '2021-12-31')).astype(int)\n",
    "    df_copy['Is_Crisis_2022'] = ((df_copy[date_col] >= '2022-01-01') & \n",
    "                                  (df_copy[date_col] <= '2022-12-31')).astype(int)\n",
    "    df_copy['Is_Recovery_Period'] = (df_copy[date_col] >= '2023-01-01').astype(int)\n",
    "    return df_copy\n",
    "\n",
    "def calculate_metrics(y_true, y_pred):\n",
    "    \"\"\"Calculate regression metrics\"\"\"\n",
    "    from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score\n",
    "    \n",
    "    mae = mean_absolute_error(y_true, y_pred)\n",
    "    rmse = np.sqrt(mean_squared_error(y_true, y_pred))\n",
    "    r2 = r2_score(y_true, y_pred)\n",
    "    mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100\n",
    "    \n",
    "    return {\n",
    "        'MAE': mae,\n",
    "        'RMSE': rmse,\n",
    "        'R2': r2,\n",
    "        'MAPE': mape\n",
    "    }\n",
    "\n",
    "def prepare_features_for_prediction(current_values, prediction_date):\n",
    "    \"\"\"\n",
    "    Prepare feature vector for a single prediction\n",
    "    current_values: dict with keys like 'petrol92', 'diesel', 'crude_oil', 'exchange_rate', etc.\n",
    "    \"\"\"\n",
    "    features = {\n",
    "        'Month': prediction_date.month,\n",
    "        'Month_Sin': np.sin(2 * np.pi * prediction_date.month / 12),\n",
    "        'Month_Cos': np.cos(2 * np.pi * prediction_date.month / 12),\n",
    "        'Quarter': (prediction_date.month - 1) // 3 + 1,\n",
    "        'Is_Weekend': 1 if prediction_date.weekday() >= 5 else 0,\n",
    "        \n",
    "        # Lag features (using current as proxy)\n",
    "        'LP_92_lag_1': current_values.get('petrol92', 0),\n",
    "        'LP_92_lag_7': current_values.get('petrol92', 0),\n",
    "        'LP_92_lag_30': current_values.get('petrol92', 0),\n",
    "        'LAD_lag_1': current_values.get('diesel', 0),\n",
    "        'LAD_lag_7': current_values.get('diesel', 0),\n",
    "        'LAD_lag_30': current_values.get('diesel', 0),\n",
    "        \n",
    "        # Rolling features\n",
    "        'LP_92_rolling_mean_7': current_values.get('petrol92', 0),\n",
    "        'LP_92_rolling_std_7': 5.0,  # Default\n",
    "        'LAD_rolling_mean_7': current_values.get('diesel', 0),\n",
    "        'LAD_rolling_std_7': 5.0,  # Default\n",
    "        \n",
    "        # Macroeconomic\n",
    "        'Crude_Oil_USD': current_values.get('crude_oil', 0),\n",
    "        'Crude_Oil_lag_7': current_values.get('crude_oil', 0),\n",
    "        'Crude_Oil_lag_30': current_values.get('crude_oil', 0),\n",
    "        'Exchange Rate': current_values.get('exchange_rate', 0),\n",
    "        'Exchange_Rate_pct_change': 0.0,\n",
    "        'Crude_Oil_LKR': current_values.get('crude_oil', 0) * current_values.get('exchange_rate', 0),\n",
    "        'GDP_Growth_Pct': current_values.get('gdp_growth', 0),\n",
    "        'Inflation_Rate': current_values.get('inflation', 0),\n",
    "        'Inflation_adj_factor': (current_values.get('inflation', 0) / 100) * current_values.get('exchange_rate', 0),\n",
    "        \n",
    "        # Holidays\n",
    "        'Is_Sinhala_Tamil_New_Year': 1 if (prediction_date.month == 4 and prediction_date.day in [13, 14]) else 0,\n",
    "        'Is_Vesak': 1 if (prediction_date.month == 5 and 15 <= prediction_date.day <= 25) else 0,\n",
    "        'Is_Christmas': 1 if (prediction_date.month == 12 and prediction_date.day == 25) else 0,\n",
    "        'Is_New_Year': 1 if (prediction_date.month == 1 and prediction_date.day == 1) else 0,\n",
    "        'Is_COVID_Period': 1 if prediction_date.year in [2020, 2021] else 0,\n",
    "        'Is_Crisis_2022': 1 if prediction_date.year == 2022 else 0,\n",
    "        'Is_Recovery_Period': 1 if prediction_date.year >= 2023 else 0\n",
    "    }\n",
    "    \n",
    "    return features"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
